name: C++ CI

on: 
  push:
    branches: [ main, trunk ] 
  pull_request:
    branches: [ main ] 

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
    - name: Build
      run: |
        gcc -o test_cache src/main.c src/cache.c -lcunit
        touch data.txt

    - name: Run tests
      run: |
        ./test_cache
